name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential git ffmpeg libsdl2-dev libsdl2-image-dev \
            libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev \
            libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev \
            libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
            libsqlite3-dev libffi-dev libssl-dev python3-setuptools
          pip install --upgrade pip
          pip install cython==0.29.36 buildozer

      - name: Build APK with Buildozer
        run: |
          rm -f buildozer.spec
          buildozer init
          
          # Konfigurasi otomatis spesifikasi Buildozer
          sed -i 's/^requirements =.*/requirements = python3,pygame,mutagen/g' buildozer.spec
          sed -i 's/^source.include_exts =.*/source.include_exts = py,png,jpg,mp3,ttf/g' buildozer.spec
          sed -i 's/#android.permissions =.*/android.permissions = READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE/g' buildozer.spec
          sed -i 's/^orientation =.*/orientation = portrait/g' buildozer.spec
          
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Premium-Player-APK
          path: .bin/*.apk
